replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/gpu0-477909/gcpcloudrun/gcpcloudrun
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: 104.198.175.33.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: gcpcloudrun-tls
      hosts:
        - 104.198.175.33.nip.io

probes:
  liveness:
    path: /healthz
    initialDelaySeconds: 10
    periodSeconds: 15
  readiness:
    path: /healthz
    initialDelaySeconds: 5
    periodSeconds: 10

rollingUpdate:
  maxUnavailable: 1

db:
  host: postgres.example.com
  port: "5432"
  name: myappdb

grpcHost: "calc-grpc:50051"

gcp:
  projectID: gpu0-477909
