apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{ .Release.Name }}-secret-store
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-secret
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: db-password
