apiVersion: apps/v1
kind: Deployment
metadata:
  name: alexk8
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: alexk8
  template:
    metadata:
      labels:
        app: alexk8
    spec:
      containers:
        - name: alexk8
          image: us-central1-docker.pkg.dev/gpu0-477909/gcpcloudrun/gcpcloudrun:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: alexk8-config
            - secretRef:
                name: alexk8-secret
          resources: {}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
