# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncalc.proto\x12\x04\x63\x61lc\"\'\n\x0fMultiplyRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"7\n\x10MultiplyResponse\x12\x0e\n\x06result\x18\x01 \x01(\x03\x12\x13\n\x0b\x63omputed_at\x18\x02 \x01(\t2G\n\nCalculator\x12\x39\n\x08Multiply\x12\x15.calc.MultiplyRequest\x1a\x16.calc.MultiplyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MULTIPLYREQUEST']._serialized_start=20
  _globals['_MULTIPLYREQUEST']._serialized_end=59
  _globals['_MULTIPLYRESPONSE']._serialized_start=61
  _globals['_MULTIPLYRESPONSE']._serialized_end=116
  _globals['_CALCULATOR']._serialized_start=118
  _globals['_CALCULATOR']._serialized_end=189
# @@protoc_insertion_point(module_scope)
